{
 "title": "Clash",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "域名访问次数",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{type=\"proxydial\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "慢 Dial",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "{type=\"proxydial\"} | json | duration > 500000",
     "maxLines": 20
    }
   ]
  },
  {
   "title": "局域网访问",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "{type=\"rulematch\"}"
    }
   ]
  },
  {
   "title": "规则匹配速度",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg_over_time({type=\"rulematch\"} | json | unwrap duration [$__range]) by (type)",
     "legendFormat": "Total"
    },
    {
     "expr": "avg_over_time({type=\"rulematch\"} | json | label_format result=`{{sub .duration .dnstime}}` | unwrap result [$__range]) by (type)",
     "legendFormat": "Exclude DNS"
    }
   ]
  },
  {
   "title": "流量统计",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (type) (sum_over_time({type=\"traffic\"} | json | unwrap down [$__interval]))"
    },
    {
     "expr": "sum by (type) (sum_over_time({type=\"traffic\"} | json | unwrap up [$__interval]))"
    }
   ]
  },
  {
   "title": "DNS 平均查询时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg_over_time({type=\"dnsrequest\"} | json | unwrap duration [$__range]) by (qType)",
     "legendFormat": "{{qType}}"
    }
   ]
  },
  {
   "title": "代理 Dial 时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg_over_time({type=\"proxydial\"} | json | unwrap duration [$__range]) by (proxy)",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "实时流量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by (type) (sum_over_time({type=\"traffic\"} | json | unwrap up [$__interval]))",
     "legendFormat": "Upload"
    },
    {
     "expr": "avg by (type) (sum_over_time({type=\"traffic\"} | json | unwrap down [$__interval]))",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "DNS 查询",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by (type) (rate({type=\"dnsrequest\"}[$__interval]))"
    }
   ]
  }
 ]
}