{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "request_id" },
   { "name": "host" }
  ]
 },
 "panels": [
  {
   "title": "Proxy Dial",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{type=\"proxydial\"} | json | host=~\".*$host.*\" and id=~\"$request_id.*\"",
     "maxLines": 300
    }
   ]
  },
  {
   "title": "DNS Request",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{type=\"dnsrequest\"} | json | name=~\".*$host.*\" and id=~\"$request_id.*\"",
     "maxLines": 300
    }
   ]
  },
  {
   "title": "Rule Match",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{type=\"rulematch\"} | json | (metadata_host=~\".*$host.*\" or metadata_dstip=~\".*$host.*\") and id=~\"$request_id.*\""
    }
   ]
  }
 ]
}